site_name: Preprocess Toolbox
theme:
  name: material
  highlightjs: true
nav:
  - Home: 'index.md'
  - 'usage.md'
  - API:
    - preprocess.dataset:
        - "preprocess_toolbox/dataset/cli.md"
        - "preprocess_toolbox/dataset/process.md"
        - "preprocess_toolbox/dataset/spatial.md"
        - "preprocess_toolbox/dataset/time.md"
    - preprocess.loader:
        - "preprocess_toolbox/loader/cli.md"
        - "preprocess_toolbox/loader/utils.md"
    - "preprocess_toolbox/base.md"
    - "preprocess_toolbox/interface.md"
    - "preprocess_toolbox/models.md"
    - "preprocess_toolbox/processor.md"
    - "preprocess_toolbox/utils.md"
    - "preprocess_toolbox/cli.md"
  - GitHub: 'https://github.com/environmental-forecasting/preprocess-toolbox'
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            heading_level: 3
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

# Include extra CSS to make some style adjustments
extra_css:
  - stylesheets/readthedocs.css

# Include extra JS to setup Read the Docs addons integrations
extra_javascript:
  - javascripts/readthedocs.js
