[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "preprocess_toolbox"
version = "0.0.1"
description = "A preprocessing toolbox for converting datasets into assets ready for ML based workloads"
readme = "README.rst"
authors = [
  {name = "James Byrne", email = "digitalinnovation@bas.ac.uk"}
]
maintainers = [
  {name = "James Byrne", email = "digitalinnovation@bas.ac.uk"}
]
classifiers = [

]
license = {text = "MIT license"}
dependencies = [
  
]

[project.optional-dependencies]
dev = [
    "coverage",  # testing
    "mypy",  # linting
    "pytest",  # testing
    "ruff"  # linting
]

[project.urls]

bugs = "https://github.com/antarctica/preprocess_toolbox/issues"
changelog = "https://github.com/antarctica/preprocess_toolbox/blob/master/changelog.md"
homepage = "https://github.com/antarctica/preprocess_toolbox"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]




# Mypy
# ----

[tool.mypy]
files = "."

# Use strict defaults
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
# Don't require test functions to include types
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"

